FORMAT: 1A
HOST: http://xo-chat.herokuapp.com/

# xo-chat

xo-chat  is a simple API allowing user  to send and receive messages


All operations use the task data object. It has following attributes:

+ roomId - unique ID of the room in form of a string 
+ text - arbitrary text content of a message, assigned by user
+ senderUserToken - unique token of the user in form string


# public chat API Root [/]


## Last  10 messages list [GET/{?token}]

+ token - unique token of the user in form string

Returns last 10 messages  on public chat and next page's link.

+ Response 200 (application/json)

    + Body

            {
                "messages":
                            [
                                {
                                    "roomID":"7",
                                    "text":"message 1",
                                    "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
                                }
                                ...
                                {
                                    "roomID":"7",
                                    "text":"message 10",
                                    "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
                                }                                
                            ],
                "paging":
                            {
                                "next": "http://xo-chat.herokuapp.com/?start_point=message_number"
                            }
            }



## Send a new message [POST]

You may send  your own message using this action. It takes a JSON
object containing a message.

+ roomId(string) - sender user`s room id
+ text(string) - Arbitrary text content
+ senderUserToken(string) - sender user`s token 

+ Request (application/json)

            {
                "roomID":"7b5be1f4-78f9-4e32-8b75",
                "text":"write something",
                "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
            }

+ Response 201



## private chat messages [/privateChat]

## Last 10 messages list[GET/{room_id}{?token}]

 
+ token - unique token of the user in form string

Returns  last 10 messages on private chat and next page's link..

+ Response 200 (application/json)

     + Body

            {
                "messages":
                            [
                                {
                                    "roomID":"7",
                                    "text":"message 1",
                                    "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
                                }
                                ...
                                {
                                    "roomID":"15",
                                    "text":"message 10",
                                    "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
                                }                                
                            ],
                "paging":
                            {
                                "next": "http://xo-chat.herokuapp.com/15/?start_point=message_number"
                            }
            }


## Send a new message [POST/{room_id}]

You may send  your own message using this action. It takes a JSON
object containing a message.

+ roomId(string) - sender user`s room id
+ text(string) - Arbitrary text content
+ senderUserToken(string) - sender user`s token 

+ Request (application/json)

            {
                "roomID":"7b5be1f4-78f9-4e32-8b75",
                "text":"write something",
                "senderUserToken":"7b5be1f4-78f9-4e32-8b75-a7e87afec327",
            }

+ Response 201
