FORMAT: 1A
HOST: http://xo-chat.herokuapp.com/

# xo-chat

xo-chat  is a simple API allowing user  to send and receive messages


All operations use the message data object. It has following attributes:

+ roomId - unique ID of the room in form of a string 
+ text - arbitrary text content of a message, assigned by user
+ senderUserToken - unique token of the user in form string


# public chat API Root [/webapi]


## List all messages [GET/{?token}]

+ token - unique token of the user in form string

Returns all messages  on public chat.

+ Response 200 (application/json)

    + Body

            [
                {
                    "roomID":"7b5be1f4-78f9-4e32-8b75",
                    "text":"write something",
                    "senderUserName":"Sanji"
                }
            ]



## Send a new message [POST/{?token}]

You may send  your own message using this action. It takes a JSON
object containing a message.

+ roomId(string) - sender user`s room id
+ text(string) - Arbitrary text content

+ Request (application/json)

            {
                "roomID":"-1",
                "text":"write something",
            }

+ Response 201


## private chat messages [/{room_id}{?token}]

## List all messages [GET]

 
+ token - unique token of the user in form string

Returns all messages  on private chat.

+ Response 200 (application/json)

    + Body

            [
                {
                    "roomID":"7b5be1f4-78f9-4e32-8b75",
                    "text":"write something",
                    "senderUserName":"Nico Robin",
                }
            ]



## Send a new message [POST]

You may send  your own message using this action. It takes a JSON
object containing a message.

+ roomId(string) - sender user`s room id
+ text(string) - Arbitrary text content

+ Request (application/json)

            {
                "roomID":"7b5be1f4-78f9-4e32-8b75",
                "text":"write something",
            }

+ Response 201
